apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: default  
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: guestbook
      port:
        number: 3000